seq = 'NNNNNNNNNNNNNAGCTAAAAAAAAAAAAAAAAAAAAAAAAAGCTTCCCCCCCCCCCCCCCCCAGCTGGGGGGGGGGGGAGCTTTTTTTTTTTAGCTNNNNNNNNNNNNN'

args.m1 = ['AG/CT', 'A/AGCTT']
args.l = 500
args.complete = 1

expected = ['CTAAAAAAAAAAAAAAAAAAAAAAAAAG', 'CTAAAAAAAAAAAAAAAAAAAAAAAAAGCT', 'CTTCCCCCCCCCCCCCCCCCAG', 'CTGGGGGGGGGGGGAG', 'CTTTTTTTTTTTAG', 'AGCTTCCCCCCCCCCCCCCCCCAG', 'AG']
